# File: configuration.yaml

viewpoints:
    from_file: false
    file_path: "../../view_space/5.txt"
    count: 100
    dimensions: 3

paths:
    log_directory: "logs"
    mesh: "./3d_models/obj_000020.ply"
    model_directory: "./3d_models"
    view_space_file: "../../view_space/100.txt"
    view_space_images_directory: "../../task1/viewspace_images"
    selected_views_directory: "../../task1/selected_views"
    target_image_directory: "../../task1/target_images"
    target_image: "../../task1/target_images/obj_000020/target_2.png"

logging:
    level: "debug" # error, critical, warn, info, debug, trace
    pattern: "[%Y-%m-%d %H:%M:%S.%e] [%^%l%$] [%n] [%t] [%s:%#] [%!] %v"

camera:
    width: 640              # Image width in pixels
    height: 480             # Image height in pixels
    fov_x: 0.95             # Field of view in degrees along x-axis
    fov_y: 0.75             # Field of view in degrees along y-axis
    focal_length:
        x: 1000.0           # Focal length along x-axis in pixels
        y: 1000.0           # Focal length along y-axis in pixels
    principal_point:
        x: 0.5              # Principal point x-coordinate (normalized)
        y: 0.5              # Principal point y-coordinate (normalized)

image:
    feature:
        extractor:
            type: "SIFT"                    # Feature extractor type (AKAZE, ORB, SIFT)"
        matcher:
            type: "FLANN"                   # Feature matcher type (FLANN, BF)
            flann:
                ratio_thresh: 0.8           # Ratio threshold for Lowe’s ratio test
                min_good_matches: 5         # Minimum number of good matches required
            bf:
                norm_type: 4                # Norm type (NORM_L2 = 4, NORM_HAMMING = 6)
                cross_check: false          # Cross-check for matching

    comparator:
        type: "COMPOSITE"                   # Selected image comparison method (FEATURE, SSIM, COMPOSITE)
        ssim:
            threshold: 0.95                 # Higher is better
        feature:
            threshold: 0.70                 # Higher is better
        composite:
            threshold: 0.60                 # Higher is better

estimation:
    distance:
        max_iterations: 5
        initial_guess: 1.7
        threshold: 0.05

rendering:
    duration: 0 # Duration of the rendering in ms

sampling:
    count: 10

convergence:
    max_iterations: 10
    threshold: 0.95
