# File: configuration.yaml

task:
    name: "task1"
    objects: "obj_000020"
    test_num: 1

viewpoints:
    from_file: false
    file_path: "../../view_space/5.txt"
    count: 100
    dimensions: 3

paths:
    log_directory: "logs"
    mesh: "./3d_models/obj_000020.ply"
    model_directory: "./3d_models"
    view_space_file: "../../view_space/100.txt"
    view_space_images_directory: "../../task1/viewspace_images"
    selected_views_directory: "../../task1/selected_views"
    target_image_directory: "../../task1/target_images"
    target_image: "../../task1/target_images/obj_000020/target.png"

logging:
    level: "trace" # info, debug, warn, error, critical, warn, trace
    pattern: "[%Y-%m-%d %H:%M:%S.%e] [%^%l%$] [%n] [%t] [%s:%#] [%!] %v"

camera:
    width: 640           # Image width in pixels
    height: 480          # Image height in pixels
    fov_x: 0.95          # Field of view in degrees along x-axis
    fov_y: 0.75          # Field of view in degrees along y-axis
    focal_length:
        x: 1000.0         # Focal length along x-axis in pixels
        y: 1000.0         # Focal length along y-axis in pixels
    principal_point:
        x: 0.5            # Principal point x-coordinate (normalized)
        y: 0.5            # Principal point y-coordinate (normalized)

optimizer:
    cmaes:
        dimensions: 3
        population_size: 30
        max_iterations: 100
        sigma: 0.5

feature_detector:
    type: "SIFT"           # Default feature detector type (SIFT or ORB)

    sift:
        n_features: 0        # Number of best features to retain, 0 means unlimited
        n_octave_layers: 3   # Number of layers in each octave
        contrast_threshold: 0.04 # Contrast threshold for filtering weak features
        edge_threshold: 10   # Edge threshold for filtering edge-like features
        sigma: 1.6           # Sigma for Gaussian used in scale-space

    orb:
        n_features: 1000      # Number of features to retain
        scale_factor: 1.1    # Scale factor for pyramid
        n_levels: 10          # Number of levels in pyramid
        edge_threshold: 31   # Size of the border where features are not detected
        first_level: 0       # Level of pyramid to start
        wta_k: 2             # Number of points to produce the oriented BRIEF descriptor
        score_type: 0        # Score type (HARRIS_SCORE = 0, FAST_SCORE = 1)
        patch_size: 31       # Size of patch for oriented BRIEF descriptor
        fast_threshold: 15   # Threshold for FAST corner detection

feature_matcher:
    type: "FLANN"          # Default feature matcher type (FLANN or BF)

    bf:
        norm_type: 4         # Norm type (NORM_L2 = 4, NORM_HAMMING = 6)
        cross_check: false   # Cross-check for matching

    flann:
        ratio_thresh: 0.8   # Ratio threshold for Lowe’s ratio test
        min_good_matches: 5 # Minimum number of good matches required

image_comparator:
    type: "FeatureBased"         # Default image comparison method (MSE or SSIM)
    mse:
        threshold: 500.0    # Lower is better
        normalize: true      # Whether to normalize the MSE score by image size
        use_mask: false      # Whether to use a mask for comparison (not implemented yet)

    ssim:
        threshold: 0.8             # Higher is better
        gaussian_window_size: 11   # Size of Gaussian window for SSIM calculation
        gaussian_sigma: 1.5        # Sigma for Gaussian window
        k1: 0.01                   # K1 constant in SSIM formula
        k2: 0.03                   # K2 constant in SSIM formula
        l: 255                     # Dynamic range of pixel values (e.g., 255 for 8-bit images)

    feature_based:
        good_match_threshold: 100.0   # Distance threshold for considering a match as good
        min_good_matches: 10          # Minimum number of good matches required
        threshold: 20.0               # Lower is better

estimation:
    distance:
        max_iterations: 100
        initial_guess: 1.7
        step_size: 0.1
        threshold: 0.005

rendering:
    duration: 0 # Duration of the rendering in ms


sampling:
    count: 50
