# File: configuration.yaml

task:
    name: "task1"
    objects: "obj_000020"
    test_num: 1

viewpoints:
    from_file: false
    file_path: "../../view_space/5.txt"
    count: 100
    dimensions: 3

paths:
    log_directory: "logs"
    mesh: "./3d_models/obj_000020.ply"
    model_directory: "./3d_models"
    view_space_file: "../../view_space/100.txt"
    view_space_images_directory: "../../task1/viewspace_images"
    selected_views_directory: "../../task1/selected_views"
    target_image_directory: "../../task1/target_images"
    target_image: "../../task1/target_images/obj_000020/target_1.png"

logging:
    level: "trace" # info, debug, warn, error, critical, warn, trace
    pattern: "[%Y-%m-%d %H:%M:%S.%e] [%^%l%$] [%n] [%t] [%s:%#] [%!] %v"

camera:
    width: 640           # Image width in pixels
    height: 480          # Image height in pixels
    fov_x: 0.95          # Field of view in degrees along x-axis
    fov_y: 0.75          # Field of view in degrees along y-axis
    focal_length:
        x: 1000.0         # Focal length along x-axis in pixels
        y: 1000.0         # Focal length along y-axis in pixels
    principal_point:
        x: 0.5            # Principal point x-coordinate (normalized)
        y: 0.5            # Principal point y-coordinate (normalized)

image:
    feature:
        extractor:
            type: "AKAZE"      # Feature extractor type (AKAZE, ORB, SIFT)"
        matcher:
            type: "FLANN"      # Feature matcher type (FLANN, BF)"
            bf:
                norm_type: 4         # Norm type (NORM_L2 = 4, NORM_HAMMING = 6)
                cross_check: false   # Cross-check for matching

            flann:
                ratio_thresh: 0.8   # Ratio threshold for Lowe’s ratio test
                min_good_matches: 5 # Minimum number of good matches required

    comparator:
        type: "SSIM"         # Default image comparison method (MSE or SSIM)
        ssim:
            threshold: 0.8             # Higher is better
            gaussian_window_size: 11   # Size of Gaussian window for SSIM calculation
            gaussian_sigma: 1.5        # Sigma for Gaussian window
            k1: 0.01                   # K1 constant in SSIM formula
            k2: 0.03                   # K2 constant in SSIM formula
            l: 255                     # Dynamic range of pixel values (e.g., 255 for 8-bit images)

        feature:
            good_match_threshold: 100.0   # Distance threshold for considering a match as good
            min_good_matches: 10          # Minimum number of good matches required
            threshold: 20.0               # Lower is better

estimation:
    distance:
        max_iterations: 5
        initial_guess: 1.7
        step_size: 0.1
        threshold: 0.05

rendering:
    duration: 0 # Duration of the rendering in ms

sampling:
    count: 10

optimization:
    pso:
        swarm_size: 10
        max_iterations: 3
        local_search_iterations: 5
        inertia_weight: 0.7
        cognitive_coefficient: 1.5
        social_coefficient: 1.5
        tolerance: 0.2
        inertia_min: 0.3
        inertia_max: 0.9
        early_termination_window: 10
        early_termination_threshold: 0.2
        velocity_max: 1.0

convergence:
    max_iterations: 10
    threshold: 0.95
