# File: docker-compose.yml

services:
    ros2_base:
        build:
            context: docker
            dockerfile: base.Dockerfile
        image: ros2_humble_opencv_base:latest
#        user: "${UID}:${GID}"  # Ensure the container runs as the host user
#        environment:
#            - USER=${USER}

    ros2:
        build:
            context: docker
            dockerfile: Dockerfile
        image: ros2_humble_xarm7:latest
        container_name: ros2_humble_xarm7
#        user: "${UID}:${GID}"
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:ro
            - .:/ros2_ws/src/ftv:rw
        environment:
            - DISPLAY=${DISPLAY}
            - QT_X11_NO_MITSHM=1
            - ROS_DOMAIN_ID=0
            - ROS_DISTRO=humble
            - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/ros2_ws/src/viewpoint_core/lib:/opt/ros/${ROS_DISTRO}/lib
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
#            - USER=${USER}
        network_mode: host
        privileged: true
        stdin_open: true
        tty: true
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]  # Ensure the GPU is allocated
        runtime: nvidia  # Use the NVIDIA runtime
        command: [ "/ros2_ws/dev_env.sh", "bash" ]
        depends_on:
            - ros2_base
