# docker-compose.yml

services:
    ros2:
        build:
            context: .
            dockerfile: Dockerfile
        image: ros2_humble_xarm7:latest
        container_name: ros2_humble_xarm7
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /run/user/${UID:-1000}/wayland-0:/run/user/${UID:-1000}/wayland-0:rw
        #      - ./ros:/ros2_ws/src/ros:rw  # Mount ROS2 project directory
        #      - ./core:/ros2_ws/src/core:rw  # Mount core project directory
        environment:
            - DISPLAY
            - WAYLAND_DISPLAY
            - QT_QPA_PLATFORM
            - XDG_RUNTIME_DIR=/run/user/${UID:-1000}
            - QT_X11_NO_MITSHM=1
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
            - ROS_DOMAIN_ID=0
            - ROS_DISTRO=humble
            - VIEWPOINT_CORE_PATH=/ros2_ws/src/core
        network_mode: host
        privileged: true
        stdin_open: true
        tty: true
        command: [ "/ros2_ws/dev_env.sh", "bash" ]
        deploy:
            resources:
                reservations:
                    devices:
                        -   driver: nvidia
                            count: all
                            capabilities: [ gpu ]