# File: docker-compose.yml

services:
    ros2_base:
        build:
            context: ./docker
            dockerfile: base.Dockerfile
        image: ros2_humble_opencv_base:latest

    ros2:
        build:
            context: ./docker
            dockerfile: Dockerfile
        image: ros2_humble_xarm7:latest
        container_name: ros2_humble_xarm7
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:ro
            - .:/ros2_ws/src/project:rw
        environment:
            - DISPLAY=${DISPLAY}
            - QT_X11_NO_MITSHM=1
            - ROS_DOMAIN_ID=0
            - ROS_DISTRO=humble
        network_mode: host
        privileged: true
        stdin_open: true
        tty: true
        command: [ "/ros2_ws/dev_env.sh", "bash" ]
        depends_on:
            - ros2_base