[tool.poetry]
name = "viewpoint-estimation"
version = "0.1.0"
description = ""
authors = ["Ayush <aym@protonmail.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
