#!/usr/bin/env bash

# Get the directory where the script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TEST_DIR="${PROJECT_ROOT}/tests"

# Function to recursively list all files in the given directory with the specified extensions
list_files() {
  local dir=$1
  shift
  local extensions=("$@")
  find "$dir" -type f \( -name "${extensions[0]}" $(printf -- ' -o -name "%s"' "${extensions[@]:1}") \) |
    sed "s|^$TEST_DIR/||"
}

# Generate test_sources.cmake file with listed test sources
generate_cmake_file() {
  local test_sources=("${!1}")

  cat >"${SCRIPT_DIR}/test_sources.cmake" <<EOL
# Automatically generated by generate_test_sources.sh
set(TEST_SOURCES
$(for source in "${test_sources[@]}"; do echo "    $source"; done)
)
EOL
}

# Define file extensions
test_extensions=("*.cpp" "*.c")

# List test source files
mapfile -t test_sources < <(list_files "${TEST_DIR}" "${test_extensions[@]}")

# Generate the CMake file
generate_cmake_file test_sources[@]

echo "test_sources.cmake generated successfully."
